"""add foreign keys and missing indexes for production readiness

Revision ID: 83b3f3c6072b
Revises: 009
Create Date: 2026-08-21 15:37:58.319354
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '83b3f3c6072b'
down_revision: Union[str, None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_api_keys_agent_id'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_audit_events_time'), table_name='audit_events')
    op.create_index('idx_audit_events_time', 'audit_events', ['occurred_at'], unique=False)
    op.create_index('idx_disputes_reported', 'disputes', ['reported_agent_id'], unique=False)
    op.create_index('idx_disputes_reporter', 'disputes', ['reporter_agent_id'], unique=False)
    op.create_index('idx_disputes_status', 'disputes', ['status'], unique=False)
    op.create_index('idx_disputes_task', 'disputes', ['task_id'], unique=False)
    op.drop_constraint(op.f('fk_disputes_reporter_agent'), 'disputes', type_='foreignkey')
    op.drop_constraint(op.f('fk_disputes_reported_agent'), 'disputes', type_='foreignkey')
    op.drop_constraint(op.f('fk_disputes_task_id'), 'disputes', type_='foreignkey')
    op.create_foreign_key(None, 'disputes', 'agents', ['reported_agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'disputes', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'disputes', 'agents', ['reporter_agent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_endorsements_to_agent'), 'endorsements', type_='foreignkey')
    op.drop_constraint(op.f('fk_endorsements_from_agent'), 'endorsements', type_='foreignkey')
    op.create_foreign_key(None, 'endorsements', 'agents', ['from_agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'endorsements', 'agents', ['to_agent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('marketplace_listings', 'tier_details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index('idx_marketplace_listings_agent', 'marketplace_listings', ['agent_id'], unique=False)
    op.drop_constraint(op.f('fk_marketplace_listings_agent'), 'marketplace_listings', type_='foreignkey')
    op.create_foreign_key(None, 'marketplace_listings', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('marketplace_usage', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('marketplace_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('idx_marketplace_usage_agent', 'marketplace_usage', ['agent_id'], unique=False)
    op.create_index('idx_marketplace_usage_listing', 'marketplace_usage', ['listing_id'], unique=False)
    op.create_foreign_key(None, 'marketplace_usage', 'marketplace_listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'marketplace_usage', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memory_objects', 'agents', ['owner_agent_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_memory_permissions_grantee', 'memory_permissions', ['grantee_agent_id'], unique=False)
    op.create_foreign_key(None, 'memory_permissions', 'agents', ['grantee_agent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('negotiation_rounds', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_neg_rounds_actor', 'negotiation_rounds', ['actor_id'], unique=False)
    op.create_foreign_key(None, 'negotiation_rounds', 'agents', ['actor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'negotiation_rounds', 'negotiations', ['negotiation_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_negotiations_requester', 'negotiations', ['requester_id'], unique=False)
    op.create_index('idx_negotiations_status', 'negotiations', ['status'], unique=False)
    op.create_index('idx_negotiations_target', 'negotiations', ['target_id'], unique=False)
    op.drop_constraint(op.f('fk_negotiations_target'), 'negotiations', type_='foreignkey')
    op.drop_constraint(op.f('fk_negotiations_requester'), 'negotiations', type_='foreignkey')
    op.create_foreign_key(None, 'negotiations', 'agents', ['target_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'negotiations', 'agents', ['requester_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_tasks_to_agent'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_workflow_id'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_from_agent'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'negotiations', ['negotiation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'agents', ['to_agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'agents', ['from_agent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_trust_score'), table_name='trust_records')
    op.create_index('idx_trust_score', 'trust_records', ['trust_score'], unique=False)
    op.drop_constraint(op.f('fk_trust_records_agent_id'), 'trust_records', type_='foreignkey')
    op.create_foreign_key(None, 'trust_records', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_workflow_tasks_task', 'workflow_tasks', ['task_id'], unique=False)
    op.drop_constraint(op.f('fk_workflow_tasks_task'), 'workflow_tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_workflow_tasks_workflow'), 'workflow_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_tasks', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workflow_tasks', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflows', 'agents', ['owner_agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_constraint(None, 'workflow_tasks', type_='foreignkey')
    op.drop_constraint(None, 'workflow_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workflow_tasks_workflow'), 'workflow_tasks', 'workflows', ['workflow_id'], ['id'])
    op.create_foreign_key(op.f('fk_workflow_tasks_task'), 'workflow_tasks', 'tasks', ['task_id'], ['id'])
    op.drop_index('idx_workflow_tasks_task', table_name='workflow_tasks')
    op.drop_constraint(None, 'trust_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_trust_records_agent_id'), 'trust_records', 'agents', ['agent_id'], ['id'])
    op.drop_index('idx_trust_score', table_name='trust_records')
    op.create_index(op.f('idx_trust_score'), 'trust_records', [sa.literal_column('trust_score DESC')], unique=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_from_agent'), 'tasks', 'agents', ['from_agent_id'], ['id'])
    op.create_foreign_key(op.f('fk_tasks_workflow_id'), 'tasks', 'workflows', ['workflow_id'], ['id'])
    op.create_foreign_key(op.f('fk_tasks_to_agent'), 'tasks', 'agents', ['to_agent_id'], ['id'])
    op.drop_constraint(None, 'negotiations', type_='foreignkey')
    op.drop_constraint(None, 'negotiations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_negotiations_requester'), 'negotiations', 'agents', ['requester_id'], ['id'])
    op.create_foreign_key(op.f('fk_negotiations_target'), 'negotiations', 'agents', ['target_id'], ['id'])
    op.drop_index('idx_negotiations_target', table_name='negotiations')
    op.drop_index('idx_negotiations_status', table_name='negotiations')
    op.drop_index('idx_negotiations_requester', table_name='negotiations')
    op.drop_constraint(None, 'negotiation_rounds', type_='foreignkey')
    op.drop_constraint(None, 'negotiation_rounds', type_='foreignkey')
    op.drop_index('idx_neg_rounds_actor', table_name='negotiation_rounds')
    op.alter_column('negotiation_rounds', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'memory_permissions', type_='foreignkey')
    op.drop_index('idx_memory_permissions_grantee', table_name='memory_permissions')
    op.drop_constraint(None, 'memory_objects', type_='foreignkey')
    op.drop_constraint(None, 'marketplace_usage', type_='foreignkey')
    op.drop_constraint(None, 'marketplace_usage', type_='foreignkey')
    op.drop_index('idx_marketplace_usage_listing', table_name='marketplace_usage')
    op.drop_index('idx_marketplace_usage_agent', table_name='marketplace_usage')
    op.alter_column('marketplace_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('marketplace_usage', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'marketplace_listings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_marketplace_listings_agent'), 'marketplace_listings', 'agents', ['agent_id'], ['id'])
    op.drop_index('idx_marketplace_listings_agent', table_name='marketplace_listings')
    op.alter_column('marketplace_listings', 'tier_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_constraint(None, 'endorsements', type_='foreignkey')
    op.drop_constraint(None, 'endorsements', type_='foreignkey')
    op.create_foreign_key(op.f('fk_endorsements_from_agent'), 'endorsements', 'agents', ['from_agent_id'], ['id'])
    op.create_foreign_key(op.f('fk_endorsements_to_agent'), 'endorsements', 'agents', ['to_agent_id'], ['id'])
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_disputes_task_id'), 'disputes', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('fk_disputes_reported_agent'), 'disputes', 'agents', ['reported_agent_id'], ['id'])
    op.create_foreign_key(op.f('fk_disputes_reporter_agent'), 'disputes', 'agents', ['reporter_agent_id'], ['id'])
    op.drop_index('idx_disputes_task', table_name='disputes')
    op.drop_index('idx_disputes_status', table_name='disputes')
    op.drop_index('idx_disputes_reporter', table_name='disputes')
    op.drop_index('idx_disputes_reported', table_name='disputes')
    op.drop_index('idx_audit_events_time', table_name='audit_events')
    op.create_index(op.f('idx_audit_events_time'), 'audit_events', [sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('fk_api_keys_agent_id'), 'api_keys', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###
